// svelte-app/src/components/AddBook.svelte
<!-- AddBook.svelte -->
<script>
    import { createEventDispatcher } from "svelte";

    export let onAddSuccess;
    export let onCancel;

    let newBookTitle = "";
    let newBookAuthor = "";
    let newBookYear = ""; // Novo campo para o ano de lançamento
    let newBookPublisher = ""; //

    const dispatch = createEventDispatcher();

    function addBook() {
        // Enviar o novo livro para a API e chamar a função de sucesso
        fetch("http://localhost:3001/books", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                title: newBookTitle,
                author: newBookAuthor,
                year: newBookYear,
                publisher: newBookPublisher,
            }),
        })
            .then((response) => response.json())
            .then((data) => {
                onAddSuccess(); // Chama a função de sucesso passada pelo componente pai
                resetForm(); // Limpar os campos após adicionar o livro
            })
            .catch((error) => {
                console.error("Error adding book: ", error);
            });
    }

    function resetForm() {
        newBookTitle = "";
        newBookAuthor = "";
        newBookYear = "";
        newBookPublisher = "";
    }

    function cancelAdd() {
        resetForm(); // Limpar os campos ao cancelar a adição
        onCancel(); // Emitir evento de cancelamento para o componente pai
    }
</script>

<div class="register-container">
    <h2 class="register-title">Adicionar livro</h2>
    <form on:submit|preventDefault={addBook}>
        <input
            class="register-input"
            type="text"
            placeholder="Título"
            bind:value={newBookTitle}
        />
        <input
            class="register-input"
            type="text"
            placeholder="Autor(a)"
            bind:value={newBookAuthor}
        />
        <input
            class="register-input"
            type="text"
            placeholder="Ano de lançamento"
            bind:value={newBookYear}
        />
        <input
            class="register-input"
            type="text"
            placeholder="Editora"
            bind:value={newBookPublisher}
        />
        <button class="register-button" type="submit">Adicionar</button>
        <button class="register-button" type="button" on:click={cancelAdd}
            >Cancelar</button
        >
    </form>
</div>

// react-app/src/components/AddBook.js
import React, { useState } from 'react';

const AddBook = ({ onAddSuccess, onCancel }) => {
  const [title, setTitle] = useState('');
  const [author, setAuthor] = useState('');
  const [year, setYear] = useState('');
  const [publisher, setPublisher] = useState('');

  const handleSubmit = (event) => {
    event.preventDefault();

    fetch('http://localhost:3001/books', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ title, author, year, publisher }),
    })
    .then(response => response.json())
    .then(data => {
      console.log('Book added: ', data);
      // Limpa os campos após adicionar um novo livro com sucesso
      setTitle('');
      setAuthor('');
      setYear('');
      setPublisher('');
      onAddSuccess(); 
    })
    .catch(error => {
      console.error('Error adding book: ', error);
    });
  };

  const handleCancel = () => {
    onCancel();
  };

  return (
    <div className='register-container'>
      <h2 className='register-title'>Adicionar novo Livro</h2>
      <form onSubmit={handleSubmit}>
          <input className='register-input' placeholder='Título' type="text" value={title} onChange={(e) => setTitle(e.target.value)} />
          <input className='register-input' placeholder='Autor(a)' type="text" value={author} onChange={(e) => setAuthor(e.target.value)} />
          <input className='register-input' placeholder='Ano de lançamento' type="text" value={year} onChange={(e) => setYear(e.target.value)} />
          <input className='register-input' placeholder='Editora' type="text" value={publisher} onChange={(e) => setPublisher(e.target.value)} />
        <button className='register-button' type="submit">Adicionar</button>
        <button className='register-button' type="button" onClick={handleCancel}>Cancelar</button>
      </form>
    </div>
  );
};

export default AddBook;
