// svelte-app/src/components/BookList.svelte
<!-- BookList.svelte -->
<script>
    import AddBook from "./AddBook.svelte";
    import UpdateBook from "./UpdateBook.svelte";
    import DeleteBook from "./DeleteBook.svelte"; // Importe o componente DeleteBook
    import ViewBook from "./ViewBook.svelte";
    import { createEventDispatcher } from "svelte";
    import './styles/styles.css'

    let showAddForm = false;
    let showUpdateForm = false;
    let showDeleteForm = false; // Variável para controlar a exibição do formulário de deleção
    let books = [];
    let selectedBookId = null;
    let selectedBookData = null;
    let showViewBook = false;
    let selectedBook = null;

    const dispatch = createEventDispatcher();

    async function fetchBooks() {
        const response = await fetch("http://localhost:3001/books");
        books = await response.json();
    }

    fetchBooks();

    async function handleAddSuccess() {
        await fetchBooks();
        toggleAddForm();
    }

    function toggleAddForm() {
        showAddForm = !showAddForm;
        if (showAddForm) {
            dispatch("addFormOpened");
        } else {
            dispatch("addFormClosed");
        }
    }

    function handleAddCancel() {
        toggleAddForm();
    }

    function toggleUpdateForm() {
        showUpdateForm = !showUpdateForm;
        if (showUpdateForm) {
            dispatch("updateFormOpened");
        } else {
            dispatch("updateFormClosed");
        }
    }

    function toggleDeleteForm() {
        showDeleteForm = !showDeleteForm;
        if (showDeleteForm) {
            dispatch("deleteFormOpened");
        } else {
            dispatch("deleteFormClosed");
        }
    }

    function toggleViewBook() {
        showViewBook = !showViewBook;
        if (showViewBook) {
            dispatch("viewBookOpened");
        } else {
            dispatch("viewBookClosed");
        }
    }

    function handleUpdateBook(id) {
        selectedBookId = id;
        selectedBookData = books.find((book) => book.id === id);
        toggleUpdateForm();
    }

    function handleUpdateCancel() {
        showUpdateForm = false;
        selectedBookId = null;
    }

    async function handleUpdateSuccess() {
        await fetchBooks();
        toggleUpdateForm();
    }

    async function deleteBook(id) {
        selectedBookId = id;
        selectedBookData = books.find((book) => book.id === id);
        toggleDeleteForm(); // Abre o formulário de deleção ao clicar no botão de deletar
    }

    async function handleDeleteSuccess() {
        await fetchBooks();
        toggleDeleteForm();
    }

    function handleDeleteCancel() {
        toggleDeleteForm();
    }

    async function handleViewBook(book) {
        selectedBook = book;
        showViewBook = true;
    }

    function handleViewCancel() {
        toggleViewBook();
    }
</script>

<div>
    {#if showAddForm}
        <AddBook onAddSuccess={handleAddSuccess} onCancel={handleAddCancel} />
    {:else if showUpdateForm}
        <UpdateBook
            id={selectedBookId}
            bookData={selectedBookData}
            onUpdateSuccess={handleUpdateSuccess}
            onCancel={handleUpdateCancel}
        />
    {:else if showDeleteForm}
        <DeleteBook
            id={selectedBookId}
            bookData={selectedBookData}
            onDeleteSuccess={handleDeleteSuccess}
            onCancel={handleDeleteCancel}
        />
    {:else if showViewBook}
        <ViewBook bookData={selectedBook} onCancel={handleViewCancel} />
    {:else}
        <div class="app-container">
            <h1>Lista de Livros</h1>
            <ul class="register-li">
                {#each books as book}
                    <li class="register-book">
                        {book.title}
                        <br />
                        {book.year}
                        <br />
                        <button
                            class="register-button"
                            on:click={() => handleUpdateBook(book.id)}
                            >Editar</button
                        >
                        <button
                            class="register-button"
                            on:click={() => deleteBook(book.id)}>Excluir</button
                        >
                        <button
                            class="register-button"
                            on:click={() => handleViewBook(book)}
                            >Visualizar</button
                        >
                    </li>
                {/each}
            </ul>
            <button class="register-button" on:click={toggleAddForm}
                >Adicionar Livro</button
            >
        </div>
    {/if}
</div>

// react-app/src/components/BookList.js
import React, { useState, useEffect } from 'react';
import UpdateBook from './UpdateBook';
import AddBook from './AddBook';
import DeleteBook from './DeleteBook';
import ViewBook from './ViewBook'; // Importe o componente ViewBook
import './styles/styles.css'


const BookList = () => {
  const [books, setBooks] = useState([]);
  const [selectedBook, setSelectedBook] = useState(null);
  const [showUpdateForm, setShowUpdateForm] = useState(false);
  const [showAddForm, setShowAddForm] = useState(false);
  const [showDeleteForm, setShowDeleteForm] = useState(false);
  const [showDetails, setShowDetails] = useState(false); // Estado para controlar a exibição dos detalhes do livro

  useEffect(() => {
    fetch('http://localhost:3001/books')
      .then(response => response.json())
      .then(data => {
        setBooks(data);
      })
      .catch(error => {
        console.error('Error fetching books: ', error);
      });
  }, []);

  const handleUpdateBook = (book) => {
    setSelectedBook(book);
    setShowUpdateForm(true);
  };

  const handleUpdateSuccess = () => {
    setShowUpdateForm(false);
    setSelectedBook(null);
    fetch('http://localhost:3001/books')
      .then(response => response.json())
      .then(data => {
        setBooks(data);
      })
      .catch(error => {
        console.error('Error fetching books: ', error);
      });
  };

  const handleCancelUpdate = () => {
    setShowUpdateForm(false);
  };

  const handleCancelAdd = () => {
    setShowAddForm(false);
  };

  const handleAddSuccess = () => {
    fetch('http://localhost:3001/books')
      .then(response => response.json())
      .then(data => {
        setBooks(data);
        setShowAddForm(false);
      })
      .catch(error => {
        console.error('Error fetching books: ', error);
      });
  };

  const handleDeleteBook = (book) => {
    setSelectedBook(book);
    setShowDeleteForm(true);
  };

  const handleDeleteSuccess = () => {
    setShowDeleteForm(false);
    setSelectedBook(null);
    fetch('http://localhost:3001/books')
      .then(response => response.json())
      .then(data => {
        setBooks(data);
      })
      .catch(error => {
        console.error('Error fetching books: ', error);
      });
  };

  const handleCancelDelete = () => {
    setShowDeleteForm(false);
  };

  const handleViewDetails = (book) => {
    setSelectedBook(book);
    setShowDetails(true);
  };

  const handleCloseDetails = () => {
    setShowDetails(false);
  };

  return (
    <div>
      {showUpdateForm ? (
        <UpdateBook
          book={selectedBook}
          onUpdateSuccess={handleUpdateSuccess}
          onCancel={handleCancelUpdate} />
      ) : showAddForm ? (
        <AddBook onAddSuccess={handleAddSuccess} onCancel={handleCancelAdd} />
      ) : showDeleteForm ? (
        <DeleteBook
          book={selectedBook}
          onDeleteSuccess={handleDeleteSuccess}
          onCancel={handleCancelDelete} />
      ) : showDetails ? (
        <ViewBook book={selectedBook}
          onClose={handleCloseDetails} />
      ) : (
        <div className='app-container'>
          <h1>Lista de Livros</h1>
          <ul className='register-li'>
            {books.map(book => (
              <li key={book.id} className='register-book'>
                {book.title}
                <br></br>
                {book.year}
                <br></br>
                <button className='register-button' onClick={() => handleUpdateBook(book)}>Editar</button>
                <button className='register-button' onClick={() => handleDeleteBook(book)}>Excluir</button>
                <button className='register-button' onClick={() => handleViewDetails(book)}>Visualizar</button>
              </li>
            ))}
          </ul>
          <button className='register-button' id='button-add' onClick={() => setShowAddForm(true)}>Adicionar Livro</button>
        </div>
      )}
      
    </div>
    
  );
};

export default BookList;
