// svelte-app/src/components/DeleteBook.svelte
<!-- DeleteBook.svelte -->
<script>
    export let id;
    export let bookData;
    export let onDeleteSuccess;
    export let onCancel;

    async function deleteBook() {
        const response = await fetch(`http://localhost:3001/books/${id}`, {
            method: "DELETE"
        });
        if (response.ok) {
            onDeleteSuccess(); // Chama a função de sucesso passada pelo componente pai
            console.log("Livro excluído com sucesso");
        } else {
            console.error("Erro ao excluir o livro:", error);
        }
    }
</script>

<div class="register-container">
    <h2 class="register-title">Excluir livro?</h2>
    <p>Título</p>
      <input class='register-input' type="text" value={bookData.title} disabled />
      <p>Autor</p>
      <input class='register-input' type="text" value={bookData.author} disabled />
      <p>Ano de lançamento</p>
      <input class='register-input' type="text" value={bookData.year} disabled />
      <p>Editora</p>
      <input class='register-input' type="text" value={bookData.publisher} disabled />
    <button class="register-button" on:click={deleteBook}>Sim</button>
    <button class="register-button" on:click={onCancel}>Cancelar</button>
</div>

// solid-app/src/components/DeleteBook.jsx
// DeleteBook.jsx

import { createSignal } from 'solid-js';

const BASE_URL = 'http://localhost:3001'; // URL base da sua API

async function deleteBook(bookId) {
    try {
        const response = await fetch(`${BASE_URL}/books/${bookId}`, {
            method: 'DELETE',
        });

        if (!response.ok) {
            throw new Error(`Erro ao deletar livro: ${response.status} - ${response.statusText}`);
        }

        // Apenas retornar true indicando sucesso
        return true;
    } catch (error) {
        console.error('Erro ao deletar livro:', error);
        return false;
    }
}

export default function DeleteBook({ book, onDelete, onCancel }) {
    const handleDelete = async () => {
        const deleted = await deleteBook(book.id);
        if (deleted) {
            onDelete(book.id); // Notifica o componente pai que o livro foi deletado
        }
    };

    return (
        <div className='register-container'>
            <h2 className='register-title'>Excluir livro?</h2>
            <p>Título</p>
            <input className='register-input' type="text" value={book.title} disabled />
            <p>Autor</p>
            <input className='register-input' type="text" value={book.author} disabled />
            <p>Ano de lançamento</p>
            <input className='register-input' type="text" value={book.year} disabled />
            <p>Editora</p>
            <input className='register-input' type="text" value={book.publisher} disabled />
            <button className='register-button' onClick={handleDelete}>Sim</button>
            <button className='register-button' onClick={onCancel}>Cancelar</button>
        </div>
    );
}
