// svelte-app/src/components/UpdateBook.svelte
<script>
    export let id;
    export let bookData;
    export let onUpdateSuccess;
    export let onCancel;

    let title = "";
    let author = "";
    let year = "";
    let publisher = "";
    let titleInput;
    let authorInput;
    let yearInput;
    let publisherInput;

    $: {
        if (bookData) {
            title = bookData.title;
            author = bookData.author;
            year = bookData.year;
            publisher = bookData.publisher;
        }
    }

    const updateBook = async () => {
        const response = await fetch(`http://localhost:3001/books/${id}`, {
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({ title, author, year, publisher }),
        });
        if (response.ok) {
            onUpdateSuccess();
            console.log("Livro atualizado com sucesso");
        } else {
            console.error("Erro de rede ou exceção:", error);
        }
    };

    function handleTitleInput(event) {
        title = event.target.value;
    }

    function handleAuthorInput(event) {
        author = event.target.value;
    }

    function handleYearInput(event) {
        year = event.target.value;
    }

    function handlePublisherInput(event) {
        publisher = event.target.value;
    }

    function cancelUpdate() {
        onCancel(); 
    }
</script>

<div class="register-container">
    <h2 class="register-title">Editar livro</h2>
    <input
        class="register-input"
        type="text"
        placeholder="Título"
        bind:this={titleInput}
        on:input={handleTitleInput}
        value={title}
    />
    <input
        class="register-input"
        type="text"
        placeholder="Autor(a)"
        bind:this={authorInput}
        on:input={handleAuthorInput}
        value={author}
    />
    <input
        class="register-input"
        type="text"
        placeholder="Ano de lançamento"
        bind:this={yearInput}
        on:input={handleYearInput}
        value={year}
    />
    <input
        class="register-input"
        type="text"
        placeholder="Editora"
        bind:this={publisherInput}
        on:input={handlePublisherInput}
        value={publisher}
    />
    <button class="register-button" on:click={() => updateBook(id)}
        >Salvar</button
    >
    <button class="register-button" type="button" on:click={cancelUpdate}
        >Cancelar</button
    >
</div>

// solid-app/src/components/UpdateBook.jsx
import { createSignal } from 'solid-js';

const BASE_URL = 'http://localhost:3001'; // URL base da sua API

async function updateBook(updatedBook) {
  try {
      const response = await fetch(`${BASE_URL}/books/${updatedBook.id}`, {
          method: 'PUT',
          headers: {
              'Content-Type': 'application/json',
          },
          body: JSON.stringify(updatedBook),
      });
      
      if (!response.ok) {
          throw new Error(`Erro ao atualizar livro: ${response.status} - ${response.statusText}`);
      }
      return true;
  } catch (error) {
      console.error('Erro ao atualizar livro:', error);
      return false;
  }
}


export function UpdateBook({ book, onUpdate, onCancel }) {
    const [updatedBook, setUpdatedBook] = createSignal(book);

    const handleSubmit = async (event) => {
        event.preventDefault();
        await updateBook(updatedBook());
        onUpdate(updatedBook()); // Atualiza localmente o livro com os novos dados
    };

    const handleInputChange = (event) => {
        const { name, value } = event.target;
        setUpdatedBook((prevBook) => ({ ...prevBook, [name]: value }));
    };

    return (
        <div className='register-container'>
            <h2 className='register-title'>Editar livro</h2>
            <form onSubmit={handleSubmit}>
                    <input className='register-input' type="text" placeholder='Título' name="title" value={updatedBook().title} onInput={handleInputChange} />
                    <input className='register-input' type="text" placeholder='Autor(a)' name="author" value={updatedBook().author} onInput={handleInputChange} />
                    <input className='register-input' type="text" placeholder='Ano de lançamento' name="year" value={updatedBook().year} onInput={handleInputChange} />
                    <input className='register-input' type="text" placeholder='Editora' name="publisher" value={updatedBook().publisher} onInput={handleInputChange} />
                <button className='register-button' type="submit">Salvar</button>
                <button className='register-button' type="button" onClick={onCancel}>Cancelar</button>
            </form>
        </div>
    );
}
