// solid-app/src/components/ViewBook.jsx
import { createSignal } from 'solid-js';

export default function ViewBook({ book, onCancel }) {
    return (
        <div className='register-container'>
            <h2 className='register-title'>Detalhes do livro</h2>
            <p>Título</p>
            <input className='register-input' type="text" value={book.title} disabled />
            <p>Autor</p>
            <input className='register-input' type="text" value={book.author} disabled />
            <p>Ano de lançamento</p>
            <input className='register-input' type="text" value={book.year} disabled />
            <p>Editora</p>
            <input className='register-input' type="text" value={book.publisher} disabled />
            <button className='register-button' onClick={onCancel}>Voltar</button>
        </div>
    );
}

// svelte-app/src/components/ViewBook.svelte
<!-- ViewBook.svelte -->
<script>
    export let bookData;
    export let onCancel;

</script>

<div class="register-container">
    <h2 class="register-title">Detalhes do livro</h2>
    <p>Título</p>
      <input class='register-input' type="text" value={bookData.title} disabled />
      <p>Autor</p>
      <input class='register-input' type="text" value={bookData.author} disabled />
      <p>Ano de lançamento</p>
      <input class='register-input' type="text" value={bookData.year} disabled />
      <p>Editora</p>
      <input class='register-input' type="text" value={bookData.publisher} disabled />
    <button class="register-button" on:click={onCancel}>Voltar</button>
</div>
